# Generated by Django 6.0.6 on 2026-07-24 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_machinetemplate_competition_difficulty_and_more'),
        ('teams', '0002_team_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='competitions.competition'),
        ),
    ]
