# Generated by Django 6.0.6 on 2026-07-24 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_machinetemplate_competition_difficulty_and_more'),
        ('injects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inject',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='injects', to='competitions.competition'),
        ),
    ]
