# Generated by Django 6.0.6 on 2026-07-24 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('os_family', models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux'), ('network', 'Network Appliance'), ('other', 'Other')], default='linux', max_length=20)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='competition',
            name='generation_mode',
            field=models.CharField(choices=[('random', 'Random'), ('precise', 'Precise')], default='random', max_length=10),
        ),
        migrations.AddField(
            model_name='competition',
            name='industry',
            field=models.CharField(choices=[('finance', 'Finance'), ('healthcare', 'Healthcare'), ('retail', 'Retail'), ('government', 'Government'), ('energy', 'Energy'), ('education', 'Education'), ('technology', 'Technology'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='competition',
            name='random_machine_count',
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('provisioning', 'Provisioning'), ('live', 'Live'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='CompetitionMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='competitions.competition')),
                ('machine_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.machinetemplate')),
            ],
        ),
    ]
